---
title: "Presentations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

**Peer-reviewed talks**

* **Macuch-Silva, V.**, Lorson, A., & Winter, B. (2023, September). _Strategic use of English quantifiers in the reporting of quantitative information_. The 10th biennial meeting of Experimental Pragmatics, Paris.

* **Macuch-Silva, V.**, Lorson, A., Kinsella, A., Woodin, G., & Winter, B. (2023, August). _A corpus analysis of English change-of-state verbs used to talk about quantity_. 16th International Cognitive Linguistics Conference, Düsseldorf.

* **Macuch-Silva, V.**, Lorson, A., & Winter, B. (2023, March). _Strategic use of quantifiers in reporting statistics_. Annual meeting of the General Psychology section of the German Psychological Society (DGPs), Trier. [<a href="https://coms.events/teap-2023-trier/data/abstracts/en/abstract_0544.html" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, & Jamieson, E (2022, February). _Interpreting negated polar questions and tracking beliefs in online discourse processing_. Workshop on Discourse obligates - How and why discourse limits the way we express what we express, 44th Annual Conference of the German Linguistics Society (DGfS), Tübingen. [<a href="https://uni-tuebingen.de/securedl/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDYwNTYxMDgsImV4cCI6MTY0NjE0NjA5OSwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW5cL1VuaV9UdWViaW5nZW5cL1NGQlwvU0ZCXzgzM1wvREdmU18yMDIyX0NvbmZlcmVuY2VfQm9va2xldF8xOC4wMi4yMDIyLnBkZiIsInBhZ2UiOjIxMTIyMn0.bNaS8CnnC1lDq6rLCmwn96Lw3W6Uv_NCoreiQr0i9Hc/DGfS_2022_Conference_Booklet_18.02.2022.pdf#page=272" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, & Jamieson, E (2021, March). _Processing polar questions in context with varying epistemic biases in English_. 34th Annual CUNY Conference on Human Sentence Processing, Philadelphia. [<a href="https://www.cuny2021.io/wp-content/uploads/2021/02/CUNY_2021_abstract_198.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, & Jamieson, E (2021, February). _Processing polar questions in context with varying epistemic biases in English_. Workshop on Biased Questions: Experimental Results & Theoretical Modelling, Berlin. [<a href="https://osf.io/cqgze/" target="_blank"><b>abstract</b></a>]

* Roberts, F., **Macuch-Silva, V.**, & Rohde, H. (2020, July [postponed to July 2021]). _Non-actual 'actual': Expectations for upcoming figurative language arise from cues about message truth_. 5th Usage-Based Linguistics Conference, Tel Aviv. [<a href="UBL-submission.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, Roberts, F., & Rohde, H. (2020, June [postponed to January 2021]). _Do truth-endorsing adjectives act as cues to non-literality in the processing of modified metaphors? A psycholinguistic investigation of English 'actual', 'literal', and 'real'_. TExMod2020: Workshop on Theoretical and
Experimental Approaches to Modification, Tübingen. [<a href="https://approachesmodificationhome.files.wordpress.com/2021/01/macuch-silva_roberts_rohde_texmod.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, & Franke, M. (2018, June). _Reading quantified expressions in context: Does pragmatic surprisal or strategic attention allocation predict self-paced reading times?_ Workshop on The pragmatics of quantifiers: implicature and presupposition – experiment and theory, Berlin.

* **Macuch-Silva, V.**, Holler, J., Özyürek, A., & Roberts, S. G. (2018). Modality-specific effects on language emergence - and why looking at interaction also matters. In H. Little & A. Micklos (Eds.), _The proceedings of the evolang xii modality matters workshop_, 16 April, 2018. [<a href="https://hlittle.com/MM/allpaperpdfs/EvoLangMM_paper3.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, Roberts, S., Holler, J., & Özyürek, A. (2017, September). _An experimental study of multimodal communication and early language emergence_. Protolang 5, Barcelona. [<a href="http://cbl.ub.edu/wp-content/uploads/2017/09/protolang5_book_of_abstracts.pdf#page=32" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, & Roberts, S. (2016) Exploring the Role of Interaction in the Emergence of Linguistic Structure. In S. Roberts & G. Mills (Eds.) _Proceedings of EvoLang XI, Language Adapts to Interaction Workshop_, 21 March, 2016. [<a href="https://evolang.org/neworleans/workshops/pdf/MacuchSilva_Lati.pdf" target="_blank"><b>abstract</b></a>]


**Conference posters**

* Lorson, A., **Macuch-Silva, V.**, Hart, C., & Winter, B (2023, September). _Using co-speech gestures strategically to influence quantifier interpretation_. The 10th biennial meeting of Experimental Pragmatics, Paris.

* **Macuch-Silva, V.**, Roettger, T., & Franke, M. (2023, June). _Processing German modal particles and predicting referents in incremental interpretation_. LingCologne 2023, Cologne. [<a href="https://lingcologne.uni-koeln.de/e-book-of-abstracts/macuch-silva-et-al-processing-german-modal-particles-and-predicting-referents-in-incremental-interpretation" target="_blank"><b>abstract</b></a>] [<a href="mouse-tracking-poster.pdf" target="_blank"><b>poster</b></a>]

* **Macuch-Silva, V.**, Lorson, A., & Winter, B. (2023, June). _Strategic use of quantifiers in reporting statistics_. 6th Mathematical Cognition and Learning Society Annual Conference, Loughborough [<a href="https://www.the-mcls.org/fileadmin/mcls/storage/conferences/2023_Loughborogh/20230517MCLS2023Programme_long_version3.pdf#page=56" target="_blank"><b>abstract</b></a>] [<a href="strategic-quantifier-poster.pdf" target="_blank"><b>poster</b></a>]

* **Macuch-Silva, V.**, Cummins, C., & Franke, M. (2020, July). _Modeling manipulative language use_. Poster presented at CogSci 2020 Virtual Conference. [<a href="https://cognitivesciencesociety.org/cogsci20/papers/0382/0382.pdf" target="_blank"><b>abstract</b></a>] [<a href="Poster-CogSci2020.pdf" target="_blank"><b>poster</b></a>]

* **Macuch-Silva, V.**, & Franke, M. (2019, November). _Do the German discourse particles eigentlich and tatsächlich modulate online expectations about intended meaning?_ Poster presented at the XPrag.de Annual Meeting, Berlin. [<a href="Poster-XPrag2019.pdf" target="_blank"><b>poster</b></a>]

* **Macuch-Silva, V.**, & Roberts, S. (2016, April). Language Adapts To Signal Disruption In Interaction. In S.G. Roberts, C. Cuskley, L. McCrohon, L. Barceló-Coblijn, O. Feher & T. Verhoef, _The Evolution of Language: Proceedings of the 11th International Conference (EVOLANG11)_. [<a href="https://evolang.org/neworleans/pdf/EVOLANG_11_paper_20.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch-Silva, V.**, & Roberts, S. (2015, June). _Does repair affect the emergence of structure in language?_ Poster presented at TABU Dag, Groningen. [<a href="Poster-TABU-Dag.pdf" target="_blank"><b>poster</b></a>]